language: python
python: "3.6"
install:
  - pip install -r requirements.txt
script:
  python test.py
notifications:
  email:
    recipients:
    - sorech02@gmail.com
    on_success: always
    on_failure: always
